# melikechan's walker config

theme = "melikechans-theme"

force_keyboard_focus = false
close_when_open = true
click_to_close = true
single_click_activation = true
selection_wrap = false
disable_mouse = false
debug = false

global_argument_delimiter = "#"
exact_search_prefix = "'"

page_jump_items = 10

hide_quick_activation = false
hide_action_hints = false
hide_action_hints_dmenu = true
hide_return_action = false
keybind_symbols = true
resume_last_query = false
actions_as_menu = false

[shell]
exclusive_zone = -1
layer = "overlay"
anchor_top = true
anchor_bottom = true
anchor_left = true
anchor_right = true

[columns]
"symbols" = 3

[placeholders]
"default" = { input = "Search", list = "No Results" }
"calc" = { input = "Calculate", list = "Enter Expression" }
"clipboard" = { input = "Clipboard", list = "Clipboard Empty" }

[keybinds]
close = ["Escape"]
next = ["Down"]
previous = ["Up"]
left = ["Left"]
right = ["Right"]
down = ["Down"]
up = ["Up"]
toggle_exact = ["ctrl e"]
resume_last_query = ["ctrl r"]
quick_activate = ["F1", "F2", "F3", "F4"]
page_down = ["Page_Down"]
page_up = ["Page_Up"]
show_actions = ["alt j"]

[providers]
default = [
  "desktopapplications",
  "calc",
  "clipboard",
  "providerlist"
]
empty = ["desktopapplications"]
ignore_preview = []
max_results = 50

[[providers.prefixes]]
prefix = ";"
provider = "providerlist"

[[providers.prefixes]]
prefix = "="
provider = "calc"

[[providers.prefixes]]
prefix = ":"
provider = "clipboard"

[providers.clipboard]
time_format = "%d.%m. - %H:%M"

[providers.actions]
fallback = [
  { action = "menus:open", label = "open", after = "Nothing" },
  { action = "menus:default", label = "run", after = "Close" },
  { action = "menus:parent", label = "back", bind = "Escape", after = "Nothing" },
  { action = "erase_history", label = "clear hist", bind = "ctrl h", after = "AsyncReload" },
]

dmenu = [{ action = "select", default = true, bind = "Return" }]

providerlist = [
  { action = "activate", default = true, bind = "Return", after = "ClearReload" },
]

calc = [
  { action = "copy", default = true, bind = "Return" },
  { action = "delete", bind = "ctrl d", after = "AsyncReload" },
  { action = "save", bind = "ctrl s", after = "AsyncClearReload" },
]

desktopapplications = [
  { action = "start", default = true, bind = "Return" },
  { action = "start:keep", label = "open+next", bind = "shift Return", after = "KeepOpen" },
  { action = "new_instance", label = "new instance", bind = "ctrl Return" },
  { action = "new_instance:keep", label = "new+next", bind = "ctrl alt Return", after = "KeepOpen" },
  { action = "pin", bind = "ctrl p", after = "AsyncReload" },
  { action = "unpin", bind = "ctrl p", after = "AsyncReload" },
  { action = "pinup", bind = "ctrl n", after = "AsyncReload" },
  { action = "pindown", bind = "ctrl m", after = "AsyncReload" },
]

clipboard = [
  { action = "copy", default = true, bind = "Return" },
  { action = "remove", bind = "ctrl d", after = "AsyncClearReload" },
  { action = "remove_all", label = "clear", bind = "ctrl shift d", after = "AsyncClearReload" },
  { action = "show_images_only", label = "only images", bind = "ctrl i", after = "AsyncClearReload" },
  { action = "show_text_only", label = "only text", bind = "ctrl i", after = "AsyncClearReload" },
  { action = "show_combined", label = "show all", bind = "ctrl i", after = "AsyncClearReload" },
  { action = "pause", bind = "ctrl p" },
  { action = "unpause", bind = "ctrl p" },
  { action = "edit", bind = "ctrl o" },
  { action = "localsend", bind = "ctrl l" },
]