# ############################ #
# melikechan's hyprlock Config #
# ############################ #

$font = Monaspace Neon NF
$outer_color = rgba(701deddd) rgba(a50d7ddd)

general {
    hide_cursor = false
    ignore_empty_input = true
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = {{ lock_screen_wallpaper_path }}
    blur_passes = 3
}

input-field {
    monitor =
    size = 20%, 5%

    position = 0, -20
    halign = center
    valign = center

    outline_thickness = 2
    rounding = 8

    dots_size = 0.3
    dots_spacing = 0.3

    fade_on_empty = false

    font_family = $font

    inner_color = rgba(100e14ff)
    font_color = rgba(edededff)

    outer_color = $outer_color 45deg
    check_color = rgba(af81f5dd) rgba(f581d7dd) 135deg
    fail_color = rgba(a50d3eee)

    # Lock doesn't change border color
    capslock_color = $outer_color 45deg
    numlock_color  = $outer_color 45deg
    bothlock_color = $outer_color 45deg

    placeholder_text = <i>Enter password...</i>
    fail_text = $PAMFAIL
}

# Time
label {
    monitor =
    text = $TIME
    font_size = 36
    font_family = $font

    position = 0, -24
    halign = center
    valign = top
}

# Date
label {
    monitor =
    text = cmd[update:60000] date +"%d %B %Y (%A)" # update every 60 seconds
    font_size = 24
    font_family = $font

    position = 0, -108
    halign = center
    valign = top
}

# Lock indicators
label {
    monitor =
    text = cmd[update:500] ~/.config/hypr/scripts/get-key-lock-state.sh
    color = rgba(edededff)
    font_size = 16
    font_family = $font
    halign = center
    valign = center
    position = 0, -80
}

# Keyboard layout
label {
    monitor =
    text = $LAYOUT[en,tr,de]
    font_size = 16
    font_family = $font

    onclick = hyprctl switchxkblayout all next

    position = 240, -20
    halign = center
    valign = center
}