# ############################# #
# melikechan's hyprpaper Config #
# ############################# #

wallpaper {
    monitor = eDP-1
    path = {{ wallpaper_path }}
    fit_mode = cover
}

splash = false