[helpers]

[default]
depends = []

[default.files]
# Folders
"hypr" = "~/.config/hypr"
"swaync" = "~/.config/swaync"
"waybar" = "~/.config/waybar"
"walker" = "~/.config/walker"
"kitty" = "~/.config/kitty"
# Standalone files
".zshrc" = "~/.zshrc"
".condarc" = "~/.condarc"
".clang-format" = "~/.clang-format"
"ruff/ruff.toml" = "~/.config/ruff/ruff.toml"

[default.variables]

# GTK theming
[gtk]
depends = []

[gtk.files]
"gtk/3.0/settings.ini" = "~/.config/gtk-3.0/settings.ini"
"gtk/4.0/settings.ini" = "~/.config/gtk-4.0/settings.ini"

[gtk.variables]

# Qt theming
[qt]
depends = []

[qt.files]
"qt6ct" = "~/.config/qt6ct"

[qt.variables]

[settings]
default_target_type = "automatic"
