[helpers]

[default]
depends = []

[default.files]
# Folders
"hypr" = "~/.config/hypr"
"swaync" = "~/.config/swaync"
"waybar" = "~/.config/waybar"
"walker" = "~/.config/walker"
"kitty" = "~/.config/kitty"
# Standalone files
".zshrc" = "~/.zshrc"
".condarc" = "~/.condarc"
"ruff/ruff.toml" = "~/.config/ruff/ruff.toml"

[default.variables]

[settings]
default_target_type = "automatic"
